### ISSUE TITLE
Analysis document (pdf file) is missing for Capstone project

### ISSUE THREAD

**Issue by JagaRamesh** [SirBowmore/Codecademy#1]
Tobias Hanauer - Please upload the Analysis document (pdf or ppt) to the GITHUB repository for project review.
https://github.com/SirBowmore/Codecademy

**Comment by SirBowmore** [comment]
Hi Jaga Ramesh,
thank you very much for your comment! Sorry, I'm totally new to github.
I just uploaded the presentation. Could you find my project at all?

Best,
Tobi

**Comment by SirBowmore** [comment]
@JagaRamesh 
Is everything ok now or is still something missing? Do you have access to all files?

Best,
Tobi
