### ISSUE TITLE
Incomplete project

### ISSUE THREAD

**Issue by sen1** [SirBowmore/Codecademy#2]
Missing presentation.

**Comment by JagaRamesh** [comment]
***** Update from Learner. The Presentation is uploaded*********

thank you very much for your comment! Sorry, I'm totally new to github.
I just uploaded the presentation. Could you find my project at all?

Best,
Tobi

**Comment by SirBowmore** [comment]
Hi @sen1 

Is everything ok now or is still something missing? Do you have access to all files?

Best,
Tobi
